# Generated by Django 5.0.6 on 2026-06-10 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.BigIntegerField(db_index=True, editable=False, unique=True)),
                ('action', models.CharField(choices=[('KEY_REGISTER', 'Key Register'), ('FILE_UPLOAD', 'File Upload'), ('FILE_DOWNLOAD', 'File Download'), ('FILE_SHARE', 'File Share'), ('FILE_ACCESS', 'File Access'), ('FILE_DELETE', 'File Delete')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prev_digest', models.CharField(blank=True, default='', max_length=64)),
                ('digest', models.CharField(db_index=True, max_length=64)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
